export const clothes = [
    {name: "Blousons - Vestes", link: "blousons_vestes"}, 
    {name: "Jeans - Pantalons", link: "jeans_pantalons"},
    {name: "Sweats - Pulls", link: "sweats_pulls"},
    {name: "T-Shirts", link: "t_shirts"},
    {name: "Ensembles", link: "ensemble"},
    {name: "Joggings", link: "joggings"},
    {name: "Sous - Vêtements", link: "sous_vetements"},
    {name: "Chemises", link: "chemises"},
    {name: "Polos", link: "polos"},
    {name: "Shorts - Bermudas", link: "shorts_bermudas"},
    {name: "Débardeurs", link: "debardeurs"},
    {name: "Robes - Jupes", link: "robes_jupes"}
];

export const topBrands = [
    {name: "adidas", link: "adidas"}, 
    {name: "BOSS", link: "boss"},
    {name: "Calvin Klein", link: "calvin_klein"},
    {name: "Comme des loups", link: "comme_des_loups"},
    {name: "Frilivin", link: "frilivin"},
    {name: "Jack And Jones", link: "jack_and_jones"},
    {name: "LBO", link: "lbo"},
    {name: "Levi's", link: "levis"},
    {name: "Schott NYC", link: "schott_nyc"},
    {name: "Sergio Tacchini", link: "sergio_tacchini"},
    {name: "Teddy Yacht Club", link: "teddy_yacht_club"},
    {name: "The North Face", link: "the_north_face"},
    {name: "Timberland", link: "timberland"},
    {name: "Tommy Hilfiger", link: "tommy_hilfiger"},
    {name: "Under Armour", link: "under_armour"},
];


export const AllShoes = [
    {name: "Baskets Basses", link: "/products/baskets_basses"}, 
    {name: "Baskets Montantes", link: "/products/baskets_montantes"},
    {name: "Bottes - Boots", link: "/products/bottes_boots"},
    {name: "Chaussures", link: "/products/chaussures"},
    {name: "Chelsea Boots", link: "/products/chelsea_boots"},
    {name: "Tongs", link: "/products/tongs"},
    {name: "Claquettes - Sandales", link: "/products/claquettes_sandales"},
    {name: "Mocassins", link: "/products/mocassins"},
    {name: "Espadrilles", link: "/products/espadrilles"},
];


export const topBrandsShoes = [
    {name: "adidas", link: "adidas"}, 
    {name: "ASICS", link: "asics"},
    {name: "BOSS", link: "boss"},
    {name: "Calvin Klein", link: "calvin_klein"},
    {name: "Levi's", link: "levis"},
    {name: "New Balance", link: "new_balance"},
    {name: "Nike", link: "nike"},
    {name: "Palladium", link: "palladium"},
    {name: "Puma", link: "puma"},
    {name: "Redskins", link: "redskins"},
    {name: "Reebok", link: "reebok"},
    {name: "Timberland", link: "timberland"},
    {name: "Tommy Hilfiger", link: "tommy_hilfiger"},
    {name: "Vans", link: "vans"},
    {name: "Versace Jeans Couture", link: "versace_jeans_couture"},
];

export const AllAccessories = [
    {name: "Sacoches - Sacs", link: "/products/sacoches_sacs"}, 
    {name: "Montres", link: "/products/montres"},
    {name: "Ceintures", link: "/products/ceintures"},
    {name: "Bracelets", link: "/products/bracelets"},
    {name: "Sacs Banane", link: "/products/sacs_banane"},
    {name: "Sacs à dos", link: "/products/sacs_a_dos"},
    {name: "Sacs à Main", link: "/products/sacs_a_main"},
    {name: "Bonnets", link: "/products/bonnets"},
    {name: "Echarpes - Foulards", link: "/products/echarpes_foulards"},
    {name: "Gants", link: "/products/gants"},
    {name: "Portefeuilles", link: "/products/portefeuilles"}, 
    {name: "Lunettes de Soleil", link: "/products/lunettes_de_soleil"},
    {name: "Colliers - Pendentifs - Bagues", link: "/products/colliers_pendentifs_bagues"},
    {name: "Accessoires de mode", link: "/products/accessoires_de_mode"}
];

export const caps = [
    {name: "Casquettes Baseball Courbées", link: "casquettes_baseball_courbees"}, 
    {name: "Casquettes Trucker", link: "casquettes_trucker"},
    {name: "Casquettes Snapbacks - Visières plates", link: "casquettes_snapbacks"},
    {name: "Bobs", link: "bobs"}
];

export const topBrandsAccessories = [
    {name: "adidas", link: "adidas"}, 
    {name: "BOSS", link: "boss"},
    {name: "California Jewels", link: "california-jewels"},
    {name: "Calvin Klein", link: "calvin-klein"},
    {name: "Casio", link: "casio"},
    {name: "Chabrand", link: "chabrand"},
    {name: "Guess", link: "guess"},
    {name: "HUGO", link: "hugo"},
    {name: "LBO", link: "lbo"},
    {name: "Levi's", link: "levis"},
    {name: "Paul Rich", link: "paul-rich"},
    {name: "The North Face", link: "the-north-face"},
    {name: "Tommy Hilfiger", link: "tommy-hilfiger"},
    {name: "Urban Classics", link: "urban-classics"},
    {name: "Versace Jeans Couture", link: "versace-jeans-couture"}, 
];

export const TopBrandLifeStyle = [
    {name: "Armita", link: "adidas"}, 
    {name: "Chabrand", link: "chabrand", sticker: "new"},
    {name: "Classic Series", link: "classic_series"},
    {name: "Comme des loups", link: "comme_des_loups", sticker: "top"},
    {name: "DC COMICS", link: "dc_comics"},
    {name: "Final Club", link: "final_club"},
    {name: "Frilivin", link: "frilivin", sticker: "new"},
    {name: "Guess", link: "guess"},
    {name: "Helvetica", link: "helvetica", sticker: "new"},
    {name: "Ikao", link: "ikao"},
    {name: "Jack And Jones", link: "jack_and_jones"},
    {name: "John H", link: "john_h"},
    {name: "Kymaxx", link: "kymaxx"},
    {name: "KZR", link: "kzr"},
    {name: "LBO", link: "lbo", sticker: "top"},
    {name: "Levi's", link: "levis", sticker: "new"},
    {name: "Luxury Lovers", link: "luxury_lovers", sticker: "new"},
    {name: "Mackten", link: "mackten"},
    {name: "Palladium", link: "palladium", sticker: "new"},
    {name: "Project X Paris", link: "project_x_paris"},
    {name: "Schott NYC", link: "schott_nyc", sticker: "new"},
    {name: "Teddy Smith", link: "teddy_smith"},
    {name: "Teddy Yatch Club", link: "urban_classics", sticker: "new"},
    {name: "Timberland", link: "timberland", sticker: "new"},
    {name: "Tommy Jeans", link: "tommy_jeans", sticker: "top"},
    {name: "UGG", link: "ugg", sticker: "new"},
    {name: "Uniplay", link: "uniplay"},
    {name: "Watts", link: "watts", sticker: "new"},
    {name: "Zayne Paris", link: "zayne_paris"},
];

export const BrandSport = [
    {name: "'47 Brand", link: "47_brand"}, 
    {name: "adidas", link: "adidas", sticker: "top"},
    {name: "Asics", link: "asics", sticker: "new"},
    {name: "Champion", link: "champion"},
    {name: "EA7 Emporio Armani", link: "EA7_emporio_armani"},
    {name: "Ellesse", link: "ellesse"},
    {name: "New Balance", link: "new_balance", sticker: "new"},
    {name: "New Era", link: "new_era"},
    {name: "Nike", link: "nike"},
    {name: "Puma", link: "puma"},
    {name: "Reebok", link: "reebok"},
    {name: "Sergio Tacchini", link: "sergio_tacchini"},
    {name: "The North Face", link: "the_north_face", sticker: "top"},
    {name: "Tommy Sport", link: "tommy_sport", sticker: "top"},
    {name: "Under Armour", link: "under_armour", sticker: "new"},
];

export const Premium = [
    {name: "Benjamin Berner", link: "benjamin_berner"}, 
    {name: "BIRKENSTOCK", link: "birkenstock"},
    {name: "BOSS", link: "boss"},
    {name: "Calvin Klein", link: "calvin_klein", sticker: "top"},
    {name: "Clarks", link: "clarks"},
    {name: "Emporio Armani", link: "emporio_armani"},
    {name: "Fred Perry", link: "fred_perry"},
    {name: "HUGO", link: "hugo"},
    {name: "K-Way", link: "k_way", sticker :"new"},
    {name: "Levi's", link: "levis", sticker :"top"},
    {name: "Polo Ralph Lauren", link: "polo_ralph_lauren"},
    {name: "Ray-Ban", link: "ray_ban"},
    {name: "Tommy Hilfiger", link: "tommy_hilfiger", sticker: "top"},
    {name: "Valentino By Mario Valentino", link: "valentino_by_mario_valentino"},
    {name: "Versace Jeans Couture", link: "versace_jeans_couture"},
];

export const hiphop = [
    {name: "Affranchis Music", link: "affranchis-music"}, 
    {name: "Booba", link: "booba", sticker: "top"},
    {name: "Da Uzi", link: "da-uzi"},
    {name: "Dala", link: "Dala"},
    {name: "Fianso", link: "fianso"},
    {name: "JSX", link: "JSX"},
    {name: "Mac Tyer", link: "mac-tyer"},
    {name: "MIG", link: "mig"},
    {name: "Ninho", link: "ninho", sticker: "top"},
    {name: "Niro", link: "niro"},
    {name: "Piraterie Music", link: "piraterie-music", sticker: "top"},
    {name: "Sale Môme", link: "sale-mome", sticker: "top"},
    {name: "Seth Gueko", link: "seth-gueko", sticker: "top"},
    {name: "Swift Guad", link: "swift-guad"},
    {name: "V2V Industry", link: "v2v-industry"},
];

export const CulteGeek = [
    {name: "Attaque des Titans", link: "attaque-des-titans"}, 
    {name: "Batman", link: "batman"},
    {name: "Bugs Bunny", link: "bugs-banny"},
    {name: "Dragon Ball Z", link: "dragonballz"},
    {name: "Looney Tunes", link: "looney-tunes", sticker: "top"},
    {name: "Manga", link: "manga", sticker: "top"},
    {name: "Naruto", link: "naruto"},
    {name: "Nasa", link: "mig", sticker: "top"},
    {name: "Nitendo", link: "nitendo"},
    {name: "One Piece", link: "onepiece", sticker: "top"},
    {name: "Super Mario", link: "super-mario"},
    {name: "Superman", link: "superman"},
    {name: "Séries TV et ...", link: "series-tv"},
    {name: "Taz", link: "taz"},
    {name: "Warner", link: "warner"},
];

export const sport = [
    {name: "SPORT", link: "sport"}, 
    {name: "AMG Mercedes", link: "amg-mercedes"},
    {name: "BMW M Motorsport", link: "bmw-m-motorsport"},
    {name: "Chicago Bulls", link: "chicago-bulls"},
    {name: "Chicago White Sox", link: "chicago-white-sox", sticker: "top"},
    {name: "F1 et Motorsport", link: "f1-motosport", sticker: "top"},
    {name: "FFF", link: "fff"},
    {name: "Foot", link: "foot", sticker: "top"},
    {name: "Juventus", link: "juventus", sticker: "top"},
    {name: "Los Angeles Dodgers", link: "los-angeles-dodgers"},
    {name: "Los Angeles Lakers", link: "los-angeles-lakers", sticker: "top"},
    {name: "MLB", link: "mlb", sticker :"top"},
    {name: "NBA", link: "nba", sticker: "top"},
    {name: "New York Yankees", link: "new-york-yankees", sticker: "top"},
    {name: "OM ", link: "om", sticker: "top"},
    {name: "PSG", link: "psg"},
];

export const informations = [
    {name: "Livraisons et retours", link: "/"},
    {name: "Aide", link: "/"},
    {name: "Avis La Brouette Officielle", link: "/"},
    {name: "Paiement 4x sans frais", link: "/"},
    {name: "Conditions Générales de Vente", link: "/"},
    {name: "Correspondance des tailles", link: "/"},
    {name: "Mentions Légales", link: "/"},
    {name: "Jobs", link: "/"},
    {name: "Code promo", link: "/"}
];


export const confidentialite = [
    {name: "Politique de confidentialité", link: "/"},
    {name: "Paramètres des données", link: "/"}
];

export const TypeClothes = [
    [
        {name: "TOUS LES BLOUSONS - VESTES", link: "/products/blousons_vestes"},
        {name: "Doudounes", link: "/products/blousons_vestes?type=Doudoune"},
        {name: "Vestes", link: "/products/blousons_vestes?type=veste"},
        {name: "Parkas", link: "/products/blousons_vestes?type=parka"},
        {name: "Bombers", link: "/products/blousons_vestes?type=bomber"},
        {name: "Doudounes Sans Manches", link: "/products/blousons_vestes?type=Doudoune Sans Manches"},
        {name: "Surchemises", link: "/products/blousons_vestes?type=surchemise"},
        {name: "Coupe-Vent", link: "/products/blousons_vestes?type=coupe_vent"},
        {name: "Vestes Biker", link: "/products/blousons_vestes?type=veste biker"},
        {name: "Manteaux", link: "/products/blousons_vestes?type=manteau"},
        {name: "Vestes Cuir", link: "/products/blousons_vestes?type=veste cuir"},
        {name: "Blazers", link: "/products/blousons_vestes?type=blazer"}
    ],
    [
        {name: "TOUS LES JEANS - PANTALONS", link: "/products/jeans_pantalons"},
        {name: "Jeans", link: "/products/jeans_pantalons?type=jean"},
        {name: "Pantalons Cargo", link: "/products/jeans_pantalons?type=pantalon cargo"},
        {name: "Chinos", link: "/products/jeans_pantalons?type=chino"},
        {name: "Jogger Pants", link: "/products/jeans_pantalons?type=jogger pants"},
        {name: "Pantalons Carreaux", link: "/products/jeans_pantalons?type=pantalon carreaux"},
        {name: "Salopettes", link: "/products/jeans_pantalons?type=salopette"}
    ],
    [
        {name: "Sweats - Pulls", link: "/products/sweats_pulls"},
        {name: "Doudounes", link: "/products/sweats_pullstype=doudoune"},
        {name: "Vestes", link: "/products/sweats_pulls?type=veste"},
        {name: "Parkas", link: "/products/sweats_pulls?type=parka"},
        {name: "Bombers", link: "/products/sweats_pulls?type=bomber"},
        {name: "Doudounes Sans Manches", link: "/products/sweats_pulls?type=doudoune sans manches"},
        {name: "Surchemises", link: "/products/sweats_pulls?type=surchemise"},
        {name: "Coupe-Vent", link: "/products/sweats_pulls?type=coupe_vent"},
        {name: "Vestes Biker", link: "/products/sweats_pulls?type=veste_biker"},
        {name: "Manteaux", link: "/products/sweats_pulls?type=manteau"},
        {name: "Vestes Cuir", link: "/products/sweats_pulls?type=veste cuir"},
        {name: "Blazers", link: "/products/sweats_pulls?type=blazer"}
    ],
    [
        {name: "TOUS LES T-SHIRTS", link: "/products/t_shirts"},
        {name: "T-Shirts Longs - Oversize", link: "/products/t_shirts?type=oversize"},
        {name: "T-Shirts Manches Longues", link: "/products/t_shirts?type=longues"},
        {name: "T-Shirts Poche", link: "/products/t_shirts?type=poche"},
        {name: "T-Shirts Capuche", link: "/products/t_shirts?type=capuche"},
    ],
    [
        {name: "TOUS LES ENSEMBLES", link: "/products/ensemble"},
        {name: "Ensembles Survêtement", link: "/products/ensemble?type=survetement"},
        {name: "Ensembles Cargo", link: "/products/ensemble?type=cargo"},
        {name: "Ensembles Lifestyle", link: "/products/ensemble?type=lifestyle"},
        {name: "Costumes", link: "/products/ensemble?type=costume"},
        {name: "Ensembles Short", link: "/products/ensemble?type=short"}
    ],
    [
        {name: "TOUS LES JOGGINGS", link: "/products/joggings"},
        {name: "Pantalons Joggings", link: "/products/joggings?type=joggings"},
        {name: "Leggings", link: "/products/joggings?type=leggings"},
    ],
    [
        {name: "SOUS - Vêtements", link: "/products/sous_vetements"},
        {name: "TOUS LES SOUS-VETEMENTS", link: "tous-les-sous-vetements"},
        {name: "Boxers", link: "boxers"},
        {name: "Chaussettes", link: "chaussettes"},
        {name: "Brassières", link: "brassieres"},
        {name: "Strings - Culottes", link: "strings-culottes"}
    ],
    [
        {name: "TOUS LES CHEMISES", link: "/products/sous_vetements"},
        {name: "Chemises Manches Longues", link: "/products/sous_vetements?type=longues"},
        {name: "Chemises Manches Courtes", link: "/products/sous_vetements?type=courtes"},  
    ],
    [
        {name: "TOUS LES POLOS", link: "/products/polos"},
        {name: "Polos Manches Longues", link: "/products/polos?type=longues"},
        {name: "Polos Manches Courtes", link: "/products/polos?type=courtes"}, 
    ],
    [
        {name: "TOUS LES SHORTS - BERMUDAS", link: "/products/shorts_bermudas"},
        {name: "Shorts Jogging", link: "/products/shorts_bermudas?type=jogging"},
        {name: "Shorts Jean", link: "/products/shorts_bermudas?type=jean"},
        {name: "Maillots de Bain", link: "/products/shorts_bermudas?type=maillots-de-bain"},
        {name: "Shorts Chinos", link: "/products/shorts_bermudas?type=chino"},
        {name: "Shorts Cargo", link: "/products/shorts_bermudas?type=cargo"}  
    ],
    [],
    [
        {name: "TOUTES LES ROBES - JUPES", link: "/products/robes_jupes"},
        {name: "Robes", link: "/products/robes_jupes?type=robe"},
        {name: "Jupes", link: "/products/robes_jupes?type=jupe"}
    ],
];

export const AllBrands = [
    {name: "'47 Brand", sticker: null, link: '47_brand'},
    {name: "2Y Premium", sticker: null,  link: '2y_premium'},
    {name: "Aarhon", sticker: null, link: 'aarhon'},
    {name: "adidas", sticker: "top", link: 'adidas'},
    {name: "ADJ", sticker: null, link: 'adj'},
    {name: "Aigle", sticker: null, link: 'aigle'},
    {name: "Alpha Industries", sticker: null, link: 'alpha_industries'},
    {name: "American People", sticker: null, link: 'american_people'},
    {name: "Anthill", sticker: null, link: 'anthill'},
    {name: "Antony Morato", sticker: null, link: 'antony_morato'},
    {name: "Armani Exchange", sticker: null, link: 'armani_exchange'},
    {name: "Armita", sticker: null, link: 'armita'},
    {name: "Asics", sticker: null, link: 'asics'},
    {name: "Barbour", sticker: null, link: 'barbour'},
    {name: "Benjamin Berner", sticker: null, link: 'benjamin_berner'},
    {name: "Billabong", sticker: null, link: 'billabong'},
    {name: "BIRKENSTOCK", sticker: null, link: 'birkenstock'},
    {name: "Black Industry", sticker: null, link: 'black_industry'},
    {name: "Black Needle", sticker: null, link: 'black_needle'},
    {name: "Blend", sticker: null, link: 'blend'},
    {name: "Bombers Original", sticker: null, link: 'bombers_original'},
    {name: "BOSS", sticker: null, link: 'boss'},
    {name: "Cacatoès", sticker: null, link: 'cacatoes'},
    {name: "California Jewels", sticker: null, link: 'california_jewels'},
    {name: "Calvin Klein", sticker: "top", link: 'calvin_klein'},
    {name: "Capslab", sticker: null, link: 'capslab'},
    {name: "Casio", sticker: null, link: 'casio'},
    {name: "Caterpillar", sticker: null, link: 'caterpillar'},
    {name: "Chabrand", sticker: null, link: 'chabrand'},
    {name: "Champion", sticker: null, link: 'champion'},
    {name: "Clarks", sticker: null, link: 'clarks'},
    {name: "Classic Series", sticker: "top", link: 'classic_series'},
    {name: "Colmar", sticker: null, link: 'colmar'},
    {name: "Columbia", sticker: null, link: 'columbia'},
    {name: "Comme Des Loups", sticker: "top", link: 'comme_des_loups'},
    {name: "Crocs", sticker: null, link: 'crocs'},
    {name: "Cross Panda", sticker: null, link: 'cross_panda'},
    {name: "DC Comics", sticker: null, link: 'dc_comics'},
    {name: "Deeluxe", sticker: null, link: 'deeluxe'},
    {name: "Dickies", sticker: null, link: 'dickies'},
    {name: "Diesel", sticker: null, link: 'diesel'},
    {name: "Dockers", sticker: null, link: 'dockers'},
    {name: "DoubleHood", sticker: null, link: 'doublehood'},
    {name: "EA7 Emporio Armani", sticker: null, link: 'ea7_emporio_armani'},
    {name: "Eastpak", sticker: null, link: 'eastpak'},
    {name: "Eden Park", sticker: null, link: 'eden_park'},
    {name: "Element", sticker: null, link: 'element'},
    {name: "Ellesse", sticker: null, link: 'ellesse'},
    {name: "Emporio Armani", sticker: null, link: 'emporio_armani'},
    {name: "Ewing Athletics", sticker: null, link: 'ewing_athletics'},
    {name: "Feiyue", sticker: null, link: 'feiyue'},
    {name: "Fila", sticker: null, link: 'fila'},
    {name: "Final Club", sticker: null, link: 'final_club'},
    {name: "Fred Perry", sticker: null, link: 'fred_perry'},
    {name: "Freegun", sticker: null, link: 'freegun'},
    {name: "Frilivin", sticker: "top", link: 'frilivin'},
    {name: "G-Star", sticker: null, link: 'g_star'},
    {name: "Gant", sticker: null, link: 'gant'},
    {name: "Gap", sticker: null, link: 'gap'},
    {name: "Geographical Norway", sticker: null, link: 'geographical_norway'},
    {name: "Girls Outfit", sticker: null, link: 'girls_outfit'},
    {name: "Goorin Bros", sticker: null, link: 'goorin_bros'},
    {name: "Guess", sticker: null, link: 'guess'},
    {name: "Havaianas", sticker: null, link: 'havaianas'},
    {name: "Helvetica", sticker: null, link: 'helvetica'},
    {name: "Horspist", sticker: null, link: 'horspist'},
    {name: "HUF", sticker: null, link: 'huf'},
    {name: "HUGO", sticker: null, link: 'hugo'},
    {name: "Icon Brand", sticker: null, link: 'icon_brand'},
    {name: "Ikao", sticker: null, link: 'ikao'},
    {name: "Indicode Jeans", sticker: null, link: 'indicode_jeans'},
    {name: "Ipanema", sticker: null, link: 'ipanema'},
    {name: "Jack And Jones", sticker: "top", link: 'jack_and_jones'},
    {name: "John H", sticker: null, link: 'john_h'},
    {name: "K-Swiss", sticker: null, link: 'k_swiss'},
    {name: "K-Way", sticker: null, link: 'k_way'},
    {name: "Kaporal", sticker: null, link: 'kaporal'},
    {name: "Kappa", sticker: null, link: 'kappa'},
    {name: "Karl Kani", sticker: null, link: 'karl_kani'},
    {name: "Kawasaki", sticker: null, link: 'kawasaki'},
    {name: "Kymaxx", sticker: null, link: 'kymaxx'},
    {name: "KZR", sticker: null, link: 'kzr'},
    {name: "LBO", sticker: "top", link: 'lbo'},
    {name: "Le Coq Sportif", sticker: null, link: 'le_coq_sportif'},
    {name: "Le Temps Des Cerises", sticker: null, link: 'le_temps_des_cerises'},
    {name: "Levi's", sticker: null, link: 'levis'},
    {name: "Luxury Lovers", sticker: null, link: 'luxury_lovers'},
    {name: "Lyle And Scott", sticker: null, link: 'lyle_and_scott'},
    {name: "Mackten", sticker: null, link: 'mackten'},
    {name: "Market", sticker: null, link: 'market'},
    {name: "Michael Kors", sticker: null, link: 'michael_kors'},
    {name: "Mitchell and Ness", sticker: null, link: 'mitchell_and_ness'},
    {name: "MTX", sticker: null, link: 'mtx'},
    {name: "MZ72", sticker: null, link: 'mz72'},
    {name: "Napapijri", sticker: null, link: 'napapijri'},
    {name: "Neochrome", sticker: null, link: 'neochrome'},
    {name: "New Balance", sticker: null, link: 'new_balance'},
    {name: "New Era", sticker: null, link: 'new_era'},
    {name: "NI by Ninho", sticker: null, link: 'ni_by_ninho'},
    {name: "Nike", sticker: null, link: 'nike'},
    {name: "Noisy May", sticker: null, link: 'noisy_may'},
    {name: "Oakley", sticker: null, link: 'oakley'},
    {name: "Okawa Sport", sticker: null, link: 'okawa_sport'},
    {name: "Only", sticker: null, link: 'only'},
    {name: "Only And Sons", sticker: null, link: 'only_and_sons'},
    {name: "Palladium", sticker: null, link: 'palladium'},
    {name: "Paname Brothers", sticker: null, link: 'paname_brothers'},
    {name: "Paul Rich", sticker: null, link: 'paul_rich'},
    {name: "Pepe Jeans", sticker: null, link: 'pepe_jeans'},
    {name: "Petrol Industries", sticker: null, link: 'petrol_industries'},
    {name: "Polo Ralph Lauren", sticker: null, link: 'polo_ralph_lauren'},
    {name: "Produkt", sticker: null, link: 'produkt'},
    {name: "Project X Paris", sticker: null, link: 'project_x_paris'},
    {name: "Puma", sticker: null, link: 'puma'},
    {name: "Quiksilver", sticker: null, link: 'quiksilver'},
    {name: "Rastaclat", sticker: null, link: 'rastaclat'},
    {name: "Ray-Ban", sticker: null, link: 'ray_ban'},
    {name: "Redfills", sticker: null, link: 'redfills'},
    {name: "Redskins", sticker: null, link: 'redskins'},
    {name: "Reebok", sticker: null, link: 'reebok'},
    {name: "Reell Jeans", sticker: null, link: 'reell_jeans'},
    {name: "Rip Curl", sticker: null, link: 'rip_curl'},
    {name: "Rivieras", sticker: null, link: 'rivieras'},
    {name: "Schott NYC", sticker: null, link: 'schott_nyc'},
    {name: "Selected", sticker: null, link: 'selected'},
    {name: "Sergio Tacchini", sticker: null, link: 'sergio_tacchini'},
    {name: "Sixth June", sticker: null, link: 'sixth_june'},
    {name: "Skr", sticker: null, link: 'skr'},
    {name: "Solid", sticker: null, link: 'solid'},
    {name: "Superdry", sticker: null, link: 'superdry'},
    {name: "Tanta", sticker: null, link: 'tanta'},
    {name: "Teddy Smith", sticker: null, link: 'teddy_smith'},
    {name: "Teddy Yacht Club", sticker: "top", link: 'teddy_yacht_club'},
    {name: "The North Face", sticker: "top", link: 'the_north_face'},
    {name: "Tiffosi", sticker: null, link: 'tiffosi'},
    {name: "Timberland", sticker: null, link: 'timberland'},
    {name: "Tom Tailor", sticker: null, link: 'tom_tailor'},
    {name: "Tommy Hilfiger", sticker: "top", link: 'tommy_hilfiger'},
    {name: "UGG", sticker: null, link: 'ugg'},
    {name: "Umbro", sticker: null, link: 'umbro'},
    {name: "Under Armour", sticker: null, link: 'under_armour'},
    {name: "Uniplay", sticker: null, link: 'uniplay'},
    {name: "Untouchable", sticker: null, link: 'untouchable'},
    {name: "Urban Classics", sticker: null, link: 'urban_classics'},
    {name: "US Polo ASSN", sticker: null, link: 'us_polo_assn'},
    {name: "Valentino By Mario Valentino", sticker: null, link: 'valentino_by_mario_valentino'},
    {name: "Vans", sticker: null, link: 'vans'},
    {name: "Venum", sticker: null, link: 'venum'},
    {name: "Vero Moda", sticker: null, link: 'vero_moda'},
    {name: "Versace Jeans Couture", sticker: null, link: 'versace_jeans_couture'},
    {name: "Victoria", sticker: null, link: 'victoria'},
    {name: "VO7", sticker: null, link: 'vo7'},
    {name: "Von Dutch", sticker: null, link: 'von_dutch'},
    {name: "Watts", sticker: "new", link: 'watts'},
    {name: "Wrung", sticker: null, link: 'wrung'},
    {name: "Y et W", sticker: null, link: 'y_et_w'},
    {name: "Zavetti Canada", sticker: null, link: 'zavetti_canada'},
    {name: "Zayne Paris", sticker: null, link: 'zayne_paris'},       
];

/* 
   Ne pas oublier de faire les liens pour les diffèrents
   thèmes de la catégorie artiste
   */  

export const AllHipHoprap = [
    {name: "Affranchis Music", link: "affranchis-music"}, 
    {name: "Booba", link: "booba", sticker: "top"},
    {name: "Da Uzi", link: "da-uzi"},
    {name: "Dala", link: "Dala"},
    {name: "Fianso", link: "fianso"},
    {name: "JSX", link: "JSX"},
    {name: "Mac Tyer", link: "mac-tyer"},
    {name: "MIG", link: "mig"},
    {name: "Ninho", link: "ninho", sticker: "top"},
    {name: "Niro", link: "niro"},
    {name: "Piraterie Music", link: "piraterie-music", sticker: "top"},
    {name: "Sale Môme", link: "sale-mome", sticker: "top"},
    {name: "Seth Gueko", link: "seth-gueko", sticker: "top"},
    {name: "Swift Guad", link: "swift-guad"},
    {name: "V2V Industry", link: "v2v-industry"},
];

export const listSizes = [
    "XS",
    "S",
    "M",
    "L",
    "XL",
    "XXL",
    "3XL",
    "4XL",
    "S/M",
    "M/L",
    "L/XL",
    "34",
    "36",
    "36.5",
    "36 2/3",
    "37",
    "37 1/3",
    "37.5",
    "38",
    "38.5",
    "38 2/3",
    "39",
    "39 1/3",
    "39.5",
    "40",
    "40 2/3",
    "40.5",
    "41",
    "41 1/3",
    "41.5",
    "42",
    "42.5",
    "42 2/3",
    "43",
    "43 1/3",
    "43.5",
    "44",
    "44.5",
    "44 2/3",
    "45",
    "45 1/3",
    "45.5",
    "46",
    "46.5",
    "46 2/3",
    "47",
    "47.5",
    "35/38",
    "37/39",
    "39/42",
    "40/41",
    "40/42",
    "41/42",
    "42/43",
    "43/45",
    "43/46",
    "43/46.5",
    "44/45",
    "T24",
    "T25",
    "T26",
    "T27",
    "T28",
    "T29",
    "T30",
    "T31",
    "T32",
    "T33",
    "T34",
    "T36",
    "T38",
    "T40",
    "T42",
    "T44",
    "T46",
    "T48",
    "T50",
    "T52",
    "T54",
    "75CM",
    "80CM",
    "85CM",
    "90CM",
    "95CM",
    "100CM",
    "105CM",
];

export const ListColors = [
    {name: "Noir", color: "#000000"},
    {name: "Blanc", color: "#FFFFFF"},
    {name: "Beige", color: "#FFF7D8"},
    {name: "Bleu", color: "#0054FF"},
    {name: "Gris", color: "#959595"},
    {name: "Kaki", color: "#647517"},
    {name: "Vert", color: "#00DD05"},
    {name: "Rose", color: "#FFBBC8"},
    {name: "Doré", color: "#B58F3C"},
    {name: "Camel", color: "#DBA400"},
    {name: "Marron", color: "#793900"},
    {name: "Rouge", color: "#FF0000"},
    {name: "Orange", color: "#FF8A00"},
    {name: "Bordeaux", color: "#6F0A2C"},
    {name: "Jaune", color: "#FFF600"},
    {name: "Violet", color: "#C600FF"},
    {name: "Argenté", color: "#B9B9B9"},
];

export const ListPromos = [
      "10",
      "15",
      "20",
      "25",
      "30",
      "35",
      "40",
      "45",
      "50",
      "55",
      "60",
      "65",
      "70",
      "75",
      "80"  
]