//        {name: "Chemises", link: "chemises"},
 
 const Tables = [
    {name: "Blousons - Vestes", link: "blousons_vestes"}, 
    {name: "Jeans - Pantalons", link: "jeans_pantalons"},
    {name: "Sweats - Pulls", link: "sweats_pulls"},
    {name: "T-Shirts", link: "t_shirts"},
    {name: "Joggings", link: "joggings"},
    {name: "Ensembles", link: "ensemble"},
    {name: "Chemises", link: "chemises"}, 
    {name: "Sous - Vêtements", link: "sous_vetements"},
    {name: "Polos", link: "polos"},
    {name: "top_ventes", link: "top_ventes_sizes"},
    {name: "Shorts - Bermudas", link: "shorts_bermudas"},
    {name: "Débardeurs", link: "debardeurs"},
    {name: "Robes - Jupes", link: "robes_jupes"},
    {name: "Sacoches - Sacs", link: "sacoches_sacs"}, 
    {name: "Montres", link: "montres"},
    {name: "Ceintures", link: "ceintures"},
    {name: "Bracelets", link: "bracelets"},
    {name: "Sacs Banane", link: "sacs_banane"},
    {name: "Sacs à dos", link: "sacs_a_dos"},
    {name: "Sacs à Main", link: "sacs_a_main"},
    {name: "Bonnets", link: "bonnets"},
    {name: "Echarpes - Foulards", link: "echarpes_foulards"},
    {name: "Gants", link: "gants"},
    {name: "Portefeuilles", link: "portefeuilles"}, 
    {name: "Lunettes de Soleil", link: "lunettes_de_soleil"},
    {name: "Colliers - Pendentifs - Bagues", link: "colliers_pendentifs_bagues"},
    {name: "Accessoires de mode", link: "accessoires_de_mode"},
    {name: "'47 Brand", sticker: null, link: '47_brand'},
    {name: "2Y Premium", sticker: null,  link: '2y_premium'},
    {name: "Aarhon", sticker: null, link: 'aarhon'},
    {name: "adidas", sticker: "top", link: 'adidas'},
    {name: "ADJ", sticker: null, link: 'adj'},
    {name: "Aigle", sticker: null, link: 'aigle'},
    {name: "Alpha Industries", sticker: null, link: 'alpha_industries'},
    {name: "American People", sticker: null, link: 'american_people'},
    {name: "Anthill", sticker: null, link: 'anthill'},
    {name: "Antony Morato", sticker: null, link: 'antony_morato'},
    {name: "Armani Exchange", sticker: null, link: 'armani_exchange'},
    {name: "Armita", sticker: null, link: 'armita'},
    {name: "Asics", sticker: null, link: 'asics'},
    {name: "Barbour", sticker: null, link: 'barbour'},
    {name: "Benjamin Berner", sticker: null, link: 'benjamin_berner'},
    {name: "Billabong", sticker: null, link: 'billabong'},
    {name: "BIRKENSTOCK", sticker: null, link: 'birkenstock'},
    {name: "Black Industry", sticker: null, link: 'black_industry'},
    {name: "Black Needle", sticker: null, link: 'black_needle'},
    {name: "Blend", sticker: null, link: 'blend'},
    {name: "Bombers Original", sticker: null, link: 'bombers_original'},
    {name: "BOSS", sticker: null, link: 'boss'},
    {name: "Cacatoès", sticker: null, link: 'cacatoes'},
    {name: "California Jewels", sticker: null, link: 'california_jewels'},
    {name: "Calvin Klein", sticker: "top", link: 'calvin_klein'},
    {name: "Capslab", sticker: null, link: 'capslab'},
    {name: "Casio", sticker: null, link: 'casio'},
    {name: "Caterpillar", sticker: null, link: 'caterpillar'},
    {name: "Chabrand", sticker: null, link: 'chabrand'},
    {name: "Champion", sticker: null, link: 'champion'},
    {name: "Clarks", sticker: null, link: 'clarks'},
    {name: "Classic Series", sticker: "top", link: 'classic_series'},
    {name: "Colmar", sticker: null, link: 'colmar'},
    {name: "Columbia", sticker: null, link: 'columbia'},
    {name: "Comme Des Loups", sticker: "top", link: 'comme_des_loups'},
    {name: "Crocs", sticker: null, link: 'crocs'},
    {name: "Cross Panda", sticker: null, link: 'cross_panda'},
    {name: "DC Comics", sticker: null, link: 'dc_comics'},
    {name: "Deeluxe", sticker: null, link: 'deeluxe'},
    {name: "Dickies", sticker: null, link: 'dickies'},
    {name: "Diesel", sticker: null, link: 'diesel'},
    {name: "Dockers", sticker: null, link: 'dockers'},
    {name: "DoubleHood", sticker: null, link: 'doublehood'},
    {name: "EA7 Emporio Armani", sticker: null, link: 'ea7_emporio_armani'},
    {name: "Eastpak", sticker: null, link: 'eastpak'},
    {name: "Eden Park", sticker: null, link: 'eden_park'},
    {name: "Element", sticker: null, link: 'element'},
    {name: "Ellesse", sticker: null, link: 'ellesse'},
    {name: "Emporio Armani", sticker: null, link: 'emporio_armani'},
    {name: "Ewing Athletics", sticker: null, link: 'ewing_athletics'},
    {name: "Feiyue", sticker: null, link: 'feiyue'},
    {name: "Fila", sticker: null, link: 'fila'},
    {name: "Final Club", sticker: null, link: 'final_club'},
    {name: "Fred Perry", sticker: null, link: 'fred_perry'},
    {name: "Freegun", sticker: null, link: 'freegun'},
    {name: "Frilivin", sticker: "top", link: 'frilivin'},
    {name: "G-Star", sticker: null, link: 'g_star'},
    {name: "Gant", sticker: null, link: 'gant'},
    {name: "Gap", sticker: null, link: 'gap'},
    {name: "Geographical Norway", sticker: null, link: 'geographical_norway'},
    {name: "Girls Outfit", sticker: null, link: 'girls_outfit'},
    {name: "Goorin Bros", sticker: null, link: 'goorin_bros'},
    {name: "Guess", sticker: null, link: 'guess'},
    {name: "Havaianas", sticker: null, link: 'havaianas'},
    {name: "Helvetica", sticker: null, link: 'helvetica'},
    {name: "Horspist", sticker: null, link: 'horspist'},
    {name: "HUF", sticker: null, link: 'huf'},
    {name: "HUGO", sticker: null, link: 'hugo'},
    {name: "Icon Brand", sticker: null, link: 'icon_brand'},
    {name: "Ikao", sticker: null, link: 'ikao'},
    {name: "Indicode Jeans", sticker: null, link: 'indicode_jeans'},
    {name: "Ipanema", sticker: null, link: 'ipanema'},
    {name: "Jack And Jones", sticker: "top", link: 'jack_and_jones'},
    {name: "John H", sticker: null, link: 'john_h'},
    {name: "K-Swiss", sticker: null, link: 'k_swiss'},
    {name: "K-Way", sticker: null, link: 'k_way'},
    {name: "Kaporal", sticker: null, link: 'kaporal'},
    {name: "Kappa", sticker: null, link: 'kappa'},
    {name: "Karl Kani", sticker: null, link: 'karl_kani'},
    {name: "Kawasaki", sticker: null, link: 'kawasaki'},
    {name: "Kymaxx", sticker: null, link: 'kymaxx'},
    {name: "KZR", sticker: null, link: 'kzr'},
    {name: "LBO", sticker: "top", link: 'lbo'},
    {name: "Le Coq Sportif", sticker: null, link: 'le_coq_sportif'},
    {name: "Le Temps Des Cerises", sticker: null, link: 'le_temps_des_cerises'},
    {name: "Levi's", sticker: null, link: 'levis'},
    {name: "Luxury Lovers", sticker: null, link: 'luxury_lovers'},
    {name: "Lyle And Scott", sticker: null, link: 'lyle_and_scott'},
    {name: "Mackten", sticker: null, link: 'mackten'},
    {name: "Market", sticker: null, link: 'market'},
    {name: "Michael Kors", sticker: null, link: 'michael_kors'},
    {name: "Mitchell and Ness", sticker: null, link: 'mitchell_and_ness'},
    {name: "MTX", sticker: null, link: 'mtx'},
    {name: "MZ72", sticker: null, link: 'mz72'},
    {name: "Napapijri", sticker: null, link: 'napapijri'},
    {name: "Neochrome", sticker: null, link: 'neochrome'},
    {name: "New Balance", sticker: null, link: 'new_balance'},
    {name: "New Era", sticker: null, link: 'new_era'},
    {name: "NI by Ninho", sticker: null, link: 'ni_by_ninho'},
    {name: "Nike", sticker: null, link: 'nike'},
    {name: "Noisy May", sticker: null, link: 'noisy_may'},
    {name: "Oakley", sticker: null, link: 'oakley'},
    {name: "Okawa Sport", sticker: null, link: 'okawa_sport'},
    {name: "Only", sticker: null, link: 'only'},
    {name: "Only And Sons", sticker: null, link: 'only_and_sons'},
    {name: "Palladium", sticker: null, link: 'palladium'},
    {name: "Paname Brothers", sticker: null, link: 'paname_brothers'},
    {name: "Paul Rich", sticker: null, link: 'paul_rich'},
    {name: "Pepe Jeans", sticker: null, link: 'pepe_jeans'},
    {name: "Petrol Industries", sticker: null, link: 'petrol_industries'},
    {name: "Polo Ralph Lauren", sticker: null, link: 'polo_ralph_lauren'},
    {name: "Produkt", sticker: null, link: 'produkt'},
    {name: "Project X Paris", sticker: null, link: 'project_x_paris'},
    {name: "Puma", sticker: null, link: 'puma'},
    {name: "Quiksilver", sticker: null, link: 'quiksilver'},
    {name: "Rastaclat", sticker: null, link: 'rastaclat'},
    {name: "Ray-Ban", sticker: null, link: 'ray_ban'},
    {name: "Redfills", sticker: null, link: 'redfills'},
    {name: "Redskins", sticker: null, link: 'redskins'},
    {name: "Reebok", sticker: null, link: 'reebok'},
    {name: "Reell Jeans", sticker: null, link: 'reell_jeans'},
    {name: "Rip Curl", sticker: null, link: 'rip_curl'},
    {name: "Rivieras", sticker: null, link: 'rivieras'},
    {name: "Schott NYC", sticker: null, link: 'schott_nyc'},
    {name: "Selected", sticker: null, link: 'selected'},
    {name: "Sergio Tacchini", sticker: null, link: 'sergio_tacchini'},
    {name: "Sixth June", sticker: null, link: 'sixth_june'},
    {name: "Skr", sticker: null, link: 'skr'},
    {name: "Solid", sticker: null, link: 'solid'},
    {name: "Superdry", sticker: null, link: 'superdry'},
    {name: "Tanta", sticker: null, link: 'tanta'},
    {name: "Teddy Smith", sticker: null, link: 'teddy_smith'},
    {name: "Teddy Yacht Club", sticker: "top", link: 'teddy_yacht_club'},
    {name: "The North Face", sticker: "top", link: 'the_north_face'},
    {name: "Tiffosi", sticker: null, link: 'tiffosi'},
    {name: "Timberland", sticker: null, link: 'timberland'},
    {name: "Tom Tailor", sticker: null, link: 'tom_tailor'},
    {name: "Tommy Hilfiger", sticker: "top", link: 'tommy_hilfiger'},
    {name: "UGG", sticker: null, link: 'ugg'},
    {name: "Umbro", sticker: null, link: 'umbro'},
    {name: "Under Armour", sticker: null, link: 'under_armour'},
    {name: "Uniplay", sticker: null, link: 'uniplay'},
    {name: "Untouchable", sticker: null, link: 'untouchable'},
    {name: "Urban Classics", sticker: null, link: 'urban_classics'},
    {name: "US Polo ASSN", sticker: null, link: 'us_polo_assn'},
    {name: "Valentino By Mario Valentino", sticker: null, link: 'valentino_by_mario_valentino'},
    {name: "Vans", sticker: null, link: 'vans'},
    {name: "Venum", sticker: null, link: 'venum'},
    {name: "Vero Moda", sticker: null, link: 'vero_moda'},
    {name: "Versace Jeans Couture", sticker: null, link: 'versace_jeans_couture'},
    {name: "Victoria", sticker: null, link: 'victoria'},
    {name: "VO7", sticker: null, link: 'vo7'},
    {name: "Von Dutch", sticker: null, link: 'von_dutch'},
    {name: "Watts", sticker: "new", link: 'watts'},
    {name: "Wrung", sticker: null, link: 'wrung'},
    {name: "Y et W", sticker: null, link: 'y_et_w'},
    {name: "Zavetti Canada", sticker: null, link: 'zavetti_canada'},
    {name: "Zayne Paris", sticker: null, link: 'zayne_paris'},
];

module.exports = {Tables}